spring:
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/step_spring_boot?serverTimezone=Asia/Shanghai
    username: root
    password: root
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true
